import type { Workspace, Group, Tag, WorkspaceGroups, GroupTags } from './types';
import { NOVELAI_TAGS } from './data/novelai-tags';

// 默认工作空间
export const DEFAULT_WORKSPACES: Workspace[] = [
  { id: 'ws_illust', name: '角色立绘', desc: '动漫插画、二次元角色，专注人物设计与表现。', color: '300', createdAt: '2026-01-15' },
  { id: 'ws_scene', name: '场景插画', desc: '环境氛围、场景概念，专注背景与空间营造。', color: '170', createdAt: '2026-03-02' },
  { id: 'ws_portrait', name: '人像写真', desc: '写实风格、摄影质感，专注人像与肖像表现。', color: '255', createdAt: '2026-04-10' },
  { id: 'ws_concept', name: '概念原画', desc: '科幻奇幻、游戏影视，专注概念设计与世界观。', color: '45', createdAt: '2026-05-20' },
];

// 默认词组
export const DEFAULT_GROUPS: Group[] = [
  { id: 'subject', name: '人物主体', desc: '年龄、性别、身份、种族等人物基本信息。', color: '300' },
  { id: 'appearance', name: '外貌特征', desc: '发型、发色、瞳色、体型等外貌细节。', color: '320' },
  { id: 'outfit', name: '服装穿搭', desc: '衣着风格、配饰道具、装备武器等。', color: '120' },
  { id: 'pose', name: '姿势动态', desc: '站姿坐姿、手势动作、身体动态等。', color: '150' },
  { id: 'expression', name: '表情神态', desc: '面部表情、情绪氛围、眼神神态等。', color: '350' },
  { id: 'scene', name: '场景背景', desc: '地点环境、天气时间、空间氛围等。', color: '170' },
  { id: 'lighting', name: '光影布光', desc: '光源类型、光影效果、明暗氛围等。', color: '45' },
  { id: 'camera', name: '镜头构图', desc: '视角景别、景深虚实、画面构图等。', color: '28' },
  { id: 'style', name: '画风媒介', desc: '艺术风格、绘画技法、材质媒介等。', color: '200' },
  { id: 'quality', name: '画面品质', desc: '分辨率、细节质感、整体质量等。', color: '220' },
  { id: 'color', name: '色彩氛围', desc: '色调配色、色彩倾向、整体色感等。', color: '280' },
  { id: 'effect', name: '特效装饰', desc: '粒子光效、自然元素、装饰点缀等。', color: '80' },
];

// 默认 Tags
export const DEFAULT_TAGS: Tag[] = [
  // 角色
  { id: 't01', en: '1girl', zh: '一个女孩', category: '角色' },
  { id: 't02', en: '1boy', zh: '一个男孩', category: '角色' },
  { id: 't03', en: '2girls', zh: '两个女孩', category: '角色' },
  { id: 't04', en: 'young_woman', zh: '年轻女性', category: '角色' },
  { id: 't05', en: 'mature_male', zh: '成熟男性', category: '角色' },
  // 画风
  { id: 't06', en: 'anime', zh: '动漫风格', category: '画风' },
  { id: 't07', en: 'realistic', zh: '写实风格', category: '画风' },
  { id: 't08', en: 'watercolor', zh: '水彩风格', category: '画风' },
  { id: 't09', en: 'oil_painting', zh: '油画风格', category: '画风' },
  { id: 't10', en: 'pixel_art', zh: '像素风格', category: '画风' },
  { id: 't11', en: 'flat_illustration', zh: '扁平插画', category: '画风' },
  { id: 't12', en: 'cel_shaded', zh: '赛璐珞风格', category: '画风' },
  // 构图
  { id: 't13', en: 'close_up', zh: '特写', category: '构图' },
  { id: 't14', en: 'full_body', zh: '全身', category: '构图' },
  { id: 't15', en: 'upper_body', zh: '半身', category: '构图' },
  { id: 't16', en: 'portrait', zh: '人像构图', category: '构图' },
  { id: 't17', en: 'wide_angle', zh: '广角', category: '构图' },
  // 光影
  { id: 't18', en: 'cinematic_lighting', zh: '电影布光', category: '光影' },
  { id: 't19', en: 'soft_lighting', zh: '柔光', category: '光影' },
  { id: 't20', en: 'dramatic_shadow', zh: '戏剧阴影', category: '光影' },
  { id: 't21', en: 'backlight', zh: '逆光', category: '光影' },
  { id: 't22', en: 'neon_light', zh: '霓虹光影', category: '光影' },
  // 画质
  { id: 't23', en: 'masterpiece', zh: '杰作', category: '画质' },
  { id: 't24', en: 'high_resolution', zh: '高分辨率', category: '画质' },
  { id: 't25', en: 'detailed_face', zh: '精细面部', category: '画质' },
  { id: 't26', en: 'best_quality', zh: '最佳质量', category: '画质' },
  // 场景
  { id: 't27', en: 'outdoor', zh: '户外', category: '场景' },
  { id: 't28', en: 'indoor', zh: '室内', category: '场景' },
  { id: 't29', en: 'city_street', zh: '城市街道', category: '场景' },
  { id: 't30', en: 'beach', zh: '海滩', category: '场景' },
  { id: 't31', en: 'snow_mountain', zh: '雪山', category: '场景' },
  { id: 't32', en: 'forest', zh: '森林', category: '场景' },
  // 色调
  { id: 't33', en: 'warm_tone', zh: '暖色调', category: '色调' },
  { id: 't34', en: 'cold_tone', zh: '冷色调', category: '色调' },
  { id: 't35', en: 'monochrome', zh: '黑白', category: '色调' },
  { id: 't36', en: 'pastel_colors', zh: '柔和色彩', category: '色调' },
  { id: 't37', en: 'solo', zh: '单人', category: '角色' },
  { id: 't38', en: 'duo', zh: '双人', category: '角色' },
  { id: 't39', en: 'group', zh: '多人', category: '角色' },
  { id: 't40', en: 'child', zh: '儿童', category: '角色' },
  { id: 't41', en: 'teenager', zh: '青少年', category: '角色' },
  { id: 't42', en: 'adult', zh: '成年人', category: '角色' },
  { id: 't43', en: 'elderly', zh: '老人', category: '角色' },
  { id: 't44', en: 'warrior', zh: '战士', category: '角色' },
  { id: 't45', en: 'mage', zh: '法师', category: '角色' },
  { id: 't46', en: 'knight', zh: '骑士', category: '角色' },
  { id: 't47', en: 'princess', zh: '公主', category: '角色' },
  { id: 't48', en: 'prince', zh: '王子', category: '角色' },
  { id: 't49', en: 'queen', zh: '女王', category: '角色' },
  { id: 't50', en: 'king', zh: '国王', category: '角色' },
  { id: 't51', en: 'idol', zh: '偶像', category: '角色' },
  { id: 't52', en: 'maid', zh: '女仆', category: '角色' },
  { id: 't53', en: 'butler', zh: '管家', category: '角色' },
  { id: 't54', en: 'student', zh: '学生', category: '角色' },
  { id: 't55', en: 'teacher', zh: '教师', category: '角色' },
  { id: 't56', en: 'detective', zh: '侦探', category: '角色' },
  { id: 't57', en: 'cyborg', zh: '半机械人', category: '角色' },
  { id: 't58', en: 'android', zh: '仿生人', category: '角色' },
  { id: 't59', en: 'elf', zh: '精灵', category: '角色' },
  { id: 't60', en: 'vampire', zh: '吸血鬼', category: '角色' },
  { id: 't61', en: 'mermaid', zh: '美人鱼', category: '角色' },
  { id: 't62', en: 'chibi', zh: 'Q版', category: '画风' },
  { id: 't63', en: 'manga_style', zh: '漫画风', category: '画风' },
  { id: 't64', en: 'comic_style', zh: '美漫风', category: '画风' },
  { id: 't65', en: 'sketch', zh: '草图', category: '画风' },
  { id: 't66', en: 'lineart', zh: '线稿', category: '画风' },
  { id: 't67', en: 'ink_drawing', zh: '墨线画', category: '画风' },
  { id: 't68', en: 'gouache', zh: '水粉', category: '画风' },
  { id: 't69', en: 'acrylic_painting', zh: '丙烯画', category: '画风' },
  { id: 't70', en: 'digital_art', zh: '数字绘画', category: '画风' },
  { id: 't71', en: 'concept_art', zh: '概念设计', category: '画风' },
  { id: 't72', en: 'matte_painting', zh: '遮罩绘景', category: '画风' },
  { id: 't73', en: 'low_poly', zh: '低多边形', category: '画风' },
  { id: 't74', en: 'isometric', zh: '等距风格', category: '画风' },
  { id: 't75', en: 'minimalist', zh: '极简风', category: '画风' },
  { id: 't76', en: 'surrealism', zh: '超现实', category: '画风' },
  { id: 't77', en: 'impressionism', zh: '印象派', category: '画风' },
  { id: 't78', en: 'baroque', zh: '巴洛克', category: '画风' },
  { id: 't79', en: 'art_nouveau', zh: '新艺术', category: '画风' },
  { id: 't80', en: 'ukiyo_e', zh: '浮世绘', category: '画风' },
  { id: 't81', en: 'paper_cut', zh: '剪纸风', category: '画风' },
  { id: 't82', en: 'front_view', zh: '正面视角', category: '构图' },
  { id: 't83', en: 'side_view', zh: '侧面视角', category: '构图' },
  { id: 't84', en: 'back_view', zh: '背面视角', category: '构图' },
  { id: 't85', en: 'three_quarter_view', zh: '四分之三视角', category: '构图' },
  { id: 't86', en: 'top_view', zh: '俯视', category: '构图' },
  { id: 't87', en: 'low_angle', zh: '低角度', category: '构图' },
  { id: 't88', en: 'high_angle', zh: '高角度', category: '构图' },
  { id: 't89', en: 'dutch_angle', zh: '倾斜构图', category: '构图' },
  { id: 't90', en: 'centered', zh: '居中构图', category: '构图' },
  { id: 't91', en: 'symmetrical', zh: '对称构图', category: '构图' },
  { id: 't92', en: 'rule_of_thirds', zh: '三分法', category: '构图' },
  { id: 't93', en: 'depth_of_field', zh: '景深', category: '构图' },
  { id: 't94', en: 'foreground_focus', zh: '前景聚焦', category: '构图' },
  { id: 't95', en: 'background_focus', zh: '背景聚焦', category: '构图' },
  { id: 't96', en: 'negative_space', zh: '留白', category: '构图' },
  { id: 't97', en: 'dynamic_composition', zh: '动态构图', category: '构图' },
  { id: 't98', en: 'diagonal_composition', zh: '对角线构图', category: '构图' },
  { id: 't99', en: 'fisheye', zh: '鱼眼', category: '构图' },
  { id: 't100', en: 'macro_shot', zh: '微距', category: '构图' },
  { id: 't101', en: 'panorama', zh: '全景', category: '构图' },
  { id: 't102', en: 'golden_hour', zh: '黄金时刻', category: '光影' },
  { id: 't103', en: 'blue_hour', zh: '蓝调时刻', category: '光影' },
  { id: 't104', en: 'rim_light', zh: '轮廓光', category: '光影' },
  { id: 't105', en: 'volumetric_light', zh: '体积光', category: '光影' },
  { id: 't106', en: 'god_rays', zh: '神圣光束', category: '光影' },
  { id: 't107', en: 'studio_light', zh: '棚拍灯光', category: '光影' },
  { id: 't108', en: 'natural_light', zh: '自然光', category: '光影' },
  { id: 't109', en: 'harsh_light', zh: '硬光', category: '光影' },
  { id: 't110', en: 'diffused_light', zh: '漫射光', category: '光影' },
  { id: 't111', en: 'spotlight', zh: '聚光灯', category: '光影' },
  { id: 't112', en: 'candlelight', zh: '烛光', category: '光影' },
  { id: 't113', en: 'moonlight', zh: '月光', category: '光影' },
  { id: 't114', en: 'sunlight', zh: '阳光', category: '光影' },
  { id: 't115', en: 'glowing', zh: '发光', category: '光影' },
  { id: 't116', en: 'silhouette', zh: '剪影', category: '光影' },
  { id: 't117', en: 'chiaroscuro', zh: '明暗对照', category: '光影' },
  { id: 't118', en: 'ambient_light', zh: '环境光', category: '光影' },
  { id: 't119', en: 'reflected_light', zh: '反射光', category: '光影' },
  { id: 't120', en: 'subsurface_scattering', zh: '次表面散射', category: '光影' },
  { id: 't121', en: 'lens_flare', zh: '镜头光晕', category: '光影' },
  { id: 't122', en: 'ultra_detailed', zh: '超精细', category: '画质' },
  { id: 't123', en: 'sharp_focus', zh: '锐利对焦', category: '画质' },
  { id: 't124', en: 'clean_lines', zh: '线条干净', category: '画质' },
  { id: 't125', en: 'high_contrast', zh: '高对比', category: '画质' },
  { id: 't126', en: 'hdr', zh: '高动态范围', category: '画质' },
  { id: 't127', en: '8k', zh: '8K', category: '画质' },
  { id: 't128', en: '4k', zh: '4K', category: '画质' },
  { id: 't129', en: 'photorealistic', zh: '照片级写实', category: '画质' },
  { id: 't130', en: 'hyperrealistic', zh: '超写实', category: '画质' },
  { id: 't131', en: 'cinematic', zh: '电影感', category: '画质' },
  { id: 't132', en: 'professional', zh: '专业质感', category: '画质' },
  { id: 't133', en: 'polished', zh: '精修', category: '画质' },
  { id: 't134', en: 'smooth_shading', zh: '平滑阴影', category: '画质' },
  { id: 't135', en: 'fine_texture', zh: '细腻纹理', category: '画质' },
  { id: 't136', en: 'rich_details', zh: '细节丰富', category: '画质' },
  { id: 't137', en: 'crisp_edges', zh: '边缘清晰', category: '画质' },
  { id: 't138', en: 'film_grain', zh: '胶片颗粒', category: '画质' },
  { id: 't139', en: 'soft_focus', zh: '柔焦', category: '画质' },
  { id: 't140', en: 'bokeh', zh: '散景', category: '画质' },
  { id: 't141', en: 'award_winning', zh: '获奖级', category: '画质' },
  { id: 't142', en: 'castle', zh: '城堡', category: '场景' },
  { id: 't143', en: 'palace', zh: '宫殿', category: '场景' },
  { id: 't144', en: 'temple', zh: '神殿', category: '场景' },
  { id: 't145', en: 'shrine', zh: '神社', category: '场景' },
  { id: 't146', en: 'library', zh: '图书馆', category: '场景' },
  { id: 't147', en: 'classroom', zh: '教室', category: '场景' },
  { id: 't148', en: 'cafe', zh: '咖啡馆', category: '场景' },
  { id: 't149', en: 'bedroom', zh: '卧室', category: '场景' },
  { id: 't150', en: 'kitchen', zh: '厨房', category: '场景' },
  { id: 't151', en: 'rooftop', zh: '屋顶', category: '场景' },
  { id: 't152', en: 'garden', zh: '花园', category: '场景' },
  { id: 't153', en: 'meadow', zh: '草地', category: '场景' },
  { id: 't154', en: 'desert', zh: '沙漠', category: '场景' },
  { id: 't155', en: 'jungle', zh: '丛林', category: '场景' },
  { id: 't156', en: 'waterfall', zh: '瀑布', category: '场景' },
  { id: 't157', en: 'lake', zh: '湖泊', category: '场景' },
  { id: 't158', en: 'ocean', zh: '海洋', category: '场景' },
  { id: 't159', en: 'space_station', zh: '空间站', category: '场景' },
  { id: 't160', en: 'cyber_city', zh: '赛博城市', category: '场景' },
  { id: 't161', en: 'ruins', zh: '遗迹', category: '场景' },
  { id: 't162', en: 'vivid_colors', zh: '鲜艳色彩', category: '色调' },
  { id: 't163', en: 'muted_colors', zh: '低饱和', category: '色调' },
  { id: 't164', en: 'high_saturation', zh: '高饱和', category: '色调' },
  { id: 't165', en: 'low_saturation', zh: '低饱和度', category: '色调' },
  { id: 't166', en: 'teal_orange', zh: '青橙色调', category: '色调' },
  { id: 't167', en: 'neon_colors', zh: '霓虹色', category: '色调' },
  { id: 't168', en: 'earth_tones', zh: '大地色', category: '色调' },
  { id: 't169', en: 'jewel_tones', zh: '宝石色', category: '色调' },
  { id: 't170', en: 'soft_palette', zh: '柔和配色', category: '色调' },
  { id: 't171', en: 'dark_palette', zh: '暗色配色', category: '色调' },
  { id: 't172', en: 'light_palette', zh: '浅色配色', category: '色调' },
  { id: 't173', en: 'gradient_colors', zh: '渐变色', category: '色调' },
  { id: 't174', en: 'iridescent', zh: '虹彩', category: '色调' },
  { id: 't175', en: 'holographic', zh: '全息色', category: '色调' },
  { id: 't176', en: 'sepia', zh: '复古棕', category: '色调' },
  { id: 't177', en: 'golden_tone', zh: '金色调', category: '色调' },
  { id: 't178', en: 'silver_tone', zh: '银色调', category: '色调' },
  { id: 't179', en: 'pink_tone', zh: '粉色调', category: '色调' },
  { id: 't180', en: 'blue_tone', zh: '蓝色调', category: '色调' },
  { id: 't181', en: 'green_tone', zh: '绿色调', category: '色调' },
  { id: 't182', en: 'smile', zh: '微笑', category: '表情' },
  { id: 't183', en: 'laughing', zh: '大笑', category: '表情' },
  { id: 't184', en: 'serious', zh: '严肃', category: '表情' },
  { id: 't185', en: 'angry', zh: '生气', category: '表情' },
  { id: 't186', en: 'sad', zh: '悲伤', category: '表情' },
  { id: 't187', en: 'crying', zh: '哭泣', category: '表情' },
  { id: 't188', en: 'surprised', zh: '惊讶', category: '表情' },
  { id: 't189', en: 'shy', zh: '害羞', category: '表情' },
  { id: 't190', en: 'confident', zh: '自信', category: '表情' },
  { id: 't191', en: 'calm', zh: '平静', category: '表情' },
  { id: 't192', en: 'sleepy', zh: '困倦', category: '表情' },
  { id: 't193', en: 'smirk', zh: '坏笑', category: '表情' },
  { id: 't194', en: 'blushing', zh: '脸红', category: '表情' },
  { id: 't195', en: 'determined', zh: '坚定', category: '表情' },
  { id: 't196', en: 'mysterious', zh: '神秘', category: '表情' },
  { id: 't197', en: 'standing', zh: '站立', category: '姿势' },
  { id: 't198', en: 'sitting', zh: '坐姿', category: '姿势' },
  { id: 't199', en: 'walking', zh: '行走', category: '姿势' },
  { id: 't200', en: 'running', zh: '奔跑', category: '姿势' },
  { id: 't201', en: 'jumping', zh: '跳跃', category: '姿势' },
  { id: 't202', en: 'kneeling', zh: '跪姿', category: '姿势' },
  { id: 't203', en: 'lying_down', zh: '躺下', category: '姿势' },
  { id: 't204', en: 'arms_crossed', zh: '双臂交叉', category: '姿势' },
  { id: 't205', en: 'hands_on_hips', zh: '叉腰', category: '姿势' },
  { id: 't206', en: 'looking_at_viewer', zh: '看向观众', category: '姿势' },
  { id: 't207', en: 'looking_away', zh: '看向别处', category: '姿势' },
  { id: 't208', en: 'reaching_out', zh: '伸手', category: '姿势' },
  { id: 't209', en: 'holding_sword', zh: '持剑', category: '姿势' },
  { id: 't210', en: 'holding_flower', zh: '持花', category: '姿势' },
  { id: 't211', en: 'peace_sign', zh: '剪刀手', category: '姿势' },
  { id: 't212', en: 'wind', zh: '风', category: '特效' },
  { id: 't213', en: 'rain', zh: '雨', category: '特效' },
  { id: 't214', en: 'snow', zh: '雪', category: '特效' },
  { id: 't215', en: 'fog', zh: '雾', category: '特效' },
  { id: 't216', en: 'smoke', zh: '烟雾', category: '特效' },
  { id: 't217', en: 'sparkles', zh: '闪光', category: '特效' },
  { id: 't218', en: 'glitter', zh: '亮片', category: '特效' },
  { id: 't219', en: 'flames', zh: '火焰', category: '特效' },
  { id: 't220', en: 'embers', zh: '余烬', category: '特效' },
  { id: 't221', en: 'lightning', zh: '闪电', category: '特效' },
  { id: 't222', en: 'magic_circle', zh: '魔法阵', category: '特效' },
  { id: 't223', en: 'aura', zh: '光环气场', category: '特效' },
  { id: 't224', en: 'energy_wave', zh: '能量波', category: '特效' },
  { id: 't225', en: 'motion_blur', zh: '动态模糊', category: '特效' },
  { id: 't226', en: 'speed_lines', zh: '速度线', category: '特效' },
  { id: 't227', en: 'floating_particles', zh: '漂浮粒子', category: '特效' },
  { id: 't228', en: 'petals', zh: '花瓣', category: '特效' },
  { id: 't229', en: 'butterflies', zh: '蝴蝶', category: '特效' },
  { id: 't230', en: 'stars', zh: '星星', category: '特效' },
  { id: 't231', en: 'galaxy', zh: '银河', category: '特效' },
  { id: 't232', en: 'crystals', zh: '水晶', category: '特效' },
  { id: 't233', en: 'bubbles', zh: '气泡', category: '特效' },
  { id: 't234', en: 'water_splash', zh: '水花', category: '特效' },
  { id: 't235', en: 'dust', zh: '尘埃', category: '特效' },
  { id: 't236', en: 'shimmer', zh: '微光', category: '特效' },
  // NovelAI 提示词
  ...NOVELAI_TAGS,
];

// 默认工作空间-词组关联
export const DEFAULT_WORKSPACE_GROUPS: WorkspaceGroups = {
  ws_illust: [
    { groupId: 'subject', type: 'positive' },
    { groupId: 'appearance', type: 'positive' },
    { groupId: 'outfit', type: 'positive' },
    { groupId: 'pose', type: 'positive' },
    { groupId: 'expression', type: 'positive' },
    { groupId: 'style', type: 'positive' },
    { groupId: 'quality', type: 'positive' },
  ],
  ws_scene: [
    { groupId: 'scene', type: 'positive' },
    { groupId: 'lighting', type: 'positive' },
    { groupId: 'camera', type: 'positive' },
    { groupId: 'style', type: 'positive' },
    { groupId: 'color', type: 'positive' },
    { groupId: 'effect', type: 'positive' },
    { groupId: 'quality', type: 'positive' },
  ],
  ws_portrait: [
    { groupId: 'subject', type: 'positive' },
    { groupId: 'appearance', type: 'positive' },
    { groupId: 'outfit', type: 'positive' },
    { groupId: 'pose', type: 'positive' },
    { groupId: 'expression', type: 'positive' },
    { groupId: 'lighting', type: 'positive' },
    { groupId: 'camera', type: 'positive' },
    { groupId: 'quality', type: 'positive' },
  ],
  ws_concept: [
    { groupId: 'subject', type: 'positive' },
    { groupId: 'outfit', type: 'positive' },
    { groupId: 'scene', type: 'positive' },
    { groupId: 'lighting', type: 'positive' },
    { groupId: 'camera', type: 'positive' },
    { groupId: 'style', type: 'positive' },
    { groupId: 'effect', type: 'positive' },
    { groupId: 'quality', type: 'positive' },
  ],
};

// 默认词组-Tag关联
export const DEFAULT_GROUP_TAGS: GroupTags = {
  subject: ['t01', 't02', 't03', 't04', 't05', 't37', 't38', 't39', 't40', 't41', 't42', 't43', 't44', 't45', 't46', 't47', 't48', 't49', 't50', 't51', 't52', 't53', 't54', 't55', 't56', 't57', 't58', 't59', 't60', 't61'],
  appearance: ['na086', 'na087', 'na088', 'na089', 'na090', 'na092', 'na093', 'na094', 'na095', 'na096', 'na097', 'na098', 'na125', 'na127', 'na128', 'na129', 'na130', 'na131'],
  outfit: ['na303', 'na304', 'na305', 'na306', 'na307', 'na314', 'na317', 'na318'],
  pose: ['t197', 't198', 't199', 't200', 't201', 't202', 't203', 't204', 't205', 't206', 't207', 't208', 't209', 't210', 't211'],
  expression: ['t182', 't183', 't184', 't185', 't186', 't187', 't188', 't189', 't190', 't191', 't192', 't193', 't194', 't195', 't196'],
  scene: ['t27', 't28', 't29', 't30', 't31', 't32', 't142', 't143', 't144', 't145', 't146', 't147', 't148', 't149', 't150', 't151', 't152', 't153', 't154', 't155', 't156', 't157', 't158', 't159', 't160', 't161'],
  lighting: ['t18', 't19', 't20', 't21', 't22', 't102', 't103', 't104', 't105', 't106', 't107', 't108', 't109', 't110', 't111', 't112', 't113', 't114', 't115', 't116', 't117', 't118', 't119', 't120', 't121'],
  camera: ['t13', 't14', 't15', 't16', 't17', 't82', 't83', 't84', 't85', 't86', 't87', 't88', 't89', 't90', 't91', 't92', 't93', 't94', 't95', 't96', 't97', 't98', 't99', 't100', 't101'],
  style: ['t06', 't07', 't08', 't09', 't10', 't11', 't12', 't62', 't63', 't64', 't65', 't66', 't67', 't68', 't69', 't70', 't71', 't72', 't73', 't74', 't75', 't76', 't77', 't78', 't79', 't80', 't81'],
  quality: ['t23', 't24', 't25', 't26', 't122', 't123', 't124', 't125', 't126', 't127', 't128', 't129', 't130', 't131', 't132', 't133', 't134', 't135', 't136', 't137', 't138', 't139', 't140', 't141'],
  color: ['t33', 't34', 't35', 't36', 't162', 't163', 't164', 't165', 't166', 't167', 't168', 't169', 't170', 't171', 't172', 't173', 't174', 't175', 't176', 't177', 't178', 't179', 't180', 't181'],
  effect: ['t212', 't213', 't214', 't215', 't216', 't217', 't218', 't219', 't220', 't221', 't222', 't223', 't224', 't225', 't226', 't227', 't228', 't229', 't230', 't231', 't232', 't233', 't234', 't235', 't236'],
};

// 主题色选项
export const COLOR_OPTIONS = ['255', '170', '145', '45', '28', '300', '200'];
